import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Header from "./components/header/Header";
import {SearchProvider} from "./context/SearchContext" 
import {QueueProvider} from "./context/QueueContext" 
import "./globals.css";
import HeaderWrapper from "./components/header/HeaderWrapper";
import { ProjectProvider } from "./context/ProjectContext";
 import Footer from "./components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "QA flow",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
   
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >   
      <SearchProvider>
        <ProjectProvider>
          <HeaderWrapper />
          <QueueProvider>
             {children}
              <Footer/>
          </QueueProvider>
        </ProjectProvider>
         
        </SearchProvider>

      </body>
    </html>
  );
}
